-- Create announcements table
CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add mood columns to attendance_logs
ALTER TABLE attendance_logs 
ADD COLUMN IF NOT EXISTS mood_status TEXT,
ADD COLUMN IF NOT EXISTS mood_note TEXT;

-- Policy to allow read access to announcements (Adjust as needed for your RLS)
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON announcements
    FOR SELECT USING (true);

CREATE POLICY "Enable insert/update for authenticated users only" ON announcements
    FOR ALL USING (auth.role() = 'authenticated');
