-- ==============================================================================
-- IN THE HAUS HR & OPERATIONS DATABASE SCHEMA
-- ==============================================================================

-- 1. Announcements Table
CREATE TABLE IF NOT EXISTS announcements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message TEXT NOT NULL,
  priority INTEGER DEFAULT 1,
  expires_at TIMESTAMP WITH TIME ZONE,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add Mood & Note columns to attendance_logs
ALTER TABLE attendance_logs 
ADD COLUMN IF NOT EXISTS mood_status TEXT,
ADD COLUMN IF NOT EXISTS mood_note TEXT;

-- 3. Job Applications Table
CREATE TABLE IF NOT EXISTS job_applications (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    full_name TEXT NOT NULL,
    position_applied TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    resume_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status TEXT DEFAULT 'Pending' CHECK (status IN ('Pending', 'Reviewing', 'Interviewed', 'Rejected', 'Hired')),
    metadata JSONB
);

-- 4. Staff Table Expansion (employees)
ALTER TABLE employees 
ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS name_en TEXT,
ADD COLUMN IF NOT EXISTS nickname TEXT,
ADD COLUMN IF NOT EXISTS phone TEXT,
ADD COLUMN IF NOT EXISTS email TEXT,
ADD COLUMN IF NOT EXISTS address TEXT,
ADD COLUMN IF NOT EXISTS id_card TEXT, 
ADD COLUMN IF NOT EXISTS employment_status TEXT CHECK (employment_status IN ('Probation', 'Fulltime', 'Contract', 'Part-time', 'Resigned', 'Suspended', 'Vacation')),
ADD COLUMN IF NOT EXISTS job_level TEXT,
ADD COLUMN IF NOT EXISTS start_date DATE,
ADD COLUMN IF NOT EXISTS probation_date DATE,
ADD COLUMN IF NOT EXISTS base_salary NUMERIC,
ADD COLUMN IF NOT EXISTS bank_account TEXT,
ADD COLUMN IF NOT EXISTS bank_name TEXT,
ADD COLUMN IF NOT EXISTS social_security_id TEXT,
ADD COLUMN IF NOT EXISTS tax_id TEXT,
ADD COLUMN IF NOT EXISTS education_history JSONB, 
ADD COLUMN IF NOT EXISTS skills TEXT[],
ADD COLUMN IF NOT EXISTS emergency_contact TEXT,
ADD COLUMN IF NOT EXISTS photo_url TEXT,
ADD COLUMN IF NOT EXISTS shift_rates JSONB DEFAULT '{
  "wage_type": "daily",
  "morning": 350,
  "evening": 400,
  "double": 800,
  "hourly_rate": 50,
  "ot_rate": 75,
  "monthly_allowance": 0,
  "diligence_allowance": 1000,
  "social_security_enrolled": false,
  "withholding_tax_pct": 0
}'::jsonb;

-- 5. Payroll Deductions & Adjustments Table
CREATE TABLE IF NOT EXISTS payroll_deductions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    month TEXT NOT NULL, -- e.g. '2026-09'
    amount NUMERIC NOT NULL,
    is_percentage BOOLEAN DEFAULT FALSE,
    reason TEXT,
    type TEXT DEFAULT 'deduction' CHECK (type IN ('deduction', 'bonus', 'advance')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_payroll_deductions_month ON payroll_deductions(month);
CREATE INDEX IF NOT EXISTS idx_payroll_deductions_emp ON payroll_deductions(employee_id);

-- 6. Payroll Global Configuration Table
CREATE TABLE IF NOT EXISTS payroll_config (
    key TEXT PRIMARY KEY,
    value NUMERIC NOT NULL,
    description TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Ensure description column exists if table was created previously
ALTER TABLE payroll_config ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE payroll_config ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();

-- Seed default payroll config if empty
INSERT INTO payroll_config (key, value, description)
VALUES 
  ('hourly_rate', 50, 'Default standard hourly rate in THB'),
  ('ot_rate', 75, 'Default standard overtime rate in THB per hour'),
  ('double_shift_rate', 800, 'Default double shift daily compensation'),
  ('diligence_default', 1000, 'Default monthly diligence bonus'),
  ('sso_rate_pct', 5, 'Social security rate percentage (5%)'),
  ('sso_cap_thb', 750, 'Maximum monthly social security deduction cap')
ON CONFLICT (key) DO NOTHING;

-- 7. Policies & RLS Configuration
ALTER TABLE announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE job_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_deductions ENABLE ROW LEVEL SECURITY;
ALTER TABLE payroll_config ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON announcements FOR SELECT USING (true);
CREATE POLICY "Enable insert/update for authenticated users only" ON announcements FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow public insert for job applications" ON job_applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow authenticated read job applications" ON job_applications FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Allow read payroll deductions for all" ON payroll_deductions FOR SELECT USING (true);
CREATE POLICY "Allow modify payroll deductions for authenticated" ON payroll_deductions FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Allow read payroll config for all" ON payroll_config FOR SELECT USING (true);
CREATE POLICY "Allow modify payroll config for authenticated" ON payroll_config FOR ALL USING (auth.role() = 'authenticated');

-- 8. Shifts Master Table & Preset Shifts
CREATE TABLE IF NOT EXISTS shifts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    code TEXT UNIQUE,
    start_time TEXT NOT NULL,
    end_time TEXT NOT NULL,
    break_minutes INTEGER DEFAULT 60,
    rate NUMERIC DEFAULT 0,
    color TEXT DEFAULT 'slate',
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE shifts ADD COLUMN IF NOT EXISTS code TEXT;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS break_minutes INTEGER DEFAULT 60;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS rate NUMERIC DEFAULT 0;
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS color TEXT DEFAULT 'slate';
ALTER TABLE shifts ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT TRUE;

ALTER TABLE shifts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read shifts for all" ON shifts FOR SELECT USING (true);
CREATE POLICY "Allow modify shifts for authenticated" ON shifts FOR ALL USING (auth.role() = 'authenticated');

-- Seed standard preset shifts
INSERT INTO shifts (id, name, code, start_time, end_time, break_minutes, rate, color, is_active)
VALUES 
  (1, 'กะเช้า (Morning)', 'morning', '07:00', '16:00', 60, 350, 'blue', true),
  (2, 'กะกลางวัน/บ่าย (Mid)', 'mid', '11:00', '20:00', 60, 380, 'amber', true),
  (3, 'กะค่ำ/ปิดร้าน (Evening)', 'evening', '15:00', '00:00', 60, 400, 'purple', true),
  (4, 'กะดึก/ข้ามคืน (Night)', 'night', '21:00', '06:00', 60, 500, 'rose', true),
  (5, 'กะควบ (Double/All-Day)', 'double', '07:00', '22:00', 120, 800, 'orange', true),
  (6, 'กะเร่งด่วน (Rush 4H)', 'rush_4h', '11:30', '15:30', 0, 220, 'emerald', true)
ON CONFLICT (id) DO UPDATE SET
  code = EXCLUDED.code,
  rate = COALESCE(shifts.rate, EXCLUDED.rate),
  color = EXCLUDED.color;

-- 9. Roster Transactions (ตารางกะงานจริงรายวัน)
CREATE TABLE IF NOT EXISTS roster_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    shift_id BIGINT REFERENCES shifts(id) ON DELETE SET NULL,
    custom_start_time TEXT,
    custom_end_time TEXT,
    slot_type TEXT DEFAULT 'MAIN',
    is_off BOOLEAN DEFAULT FALSE,
    status TEXT DEFAULT 'PUBLISHED',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_roster_tx_date ON roster_transactions(date);
CREATE INDEX IF NOT EXISTS idx_roster_tx_emp ON roster_transactions(employee_id);
ALTER TABLE roster_transactions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read roster_transactions for all" ON roster_transactions FOR SELECT USING (true);
CREATE POLICY "Allow modify roster_transactions for authenticated" ON roster_transactions FOR ALL USING (auth.role() = 'authenticated');

-- 10. Weekly Template Schedules (ตารางงานเทมเพลตประจำสัปดาห์)
CREATE TABLE IF NOT EXISTS employee_schedules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    day_of_week INTEGER NOT NULL, -- 0 (Sun) to 6 (Sat)
    shift_id BIGINT REFERENCES shifts(id) ON DELETE SET NULL,
    is_off BOOLEAN DEFAULT FALSE,
    custom_start_time TEXT,
    custom_end_time TEXT,
    slot_type TEXT DEFAULT 'MAIN',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE employee_schedules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read employee_schedules for all" ON employee_schedules FOR SELECT USING (true);
CREATE POLICY "Allow modify employee_schedules for authenticated" ON employee_schedules FOR ALL USING (auth.role() = 'authenticated');

-- 11. Leave Requests Table (คำขอลาหยุดงาน)
CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
    leave_date DATE NOT NULL,
    leave_type TEXT NOT NULL DEFAULT 'sick',
    reason TEXT,
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    replacement_employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leave_requests_date ON leave_requests(leave_date);
ALTER TABLE leave_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read leave_requests for all" ON leave_requests FOR SELECT USING (true);
CREATE POLICY "Allow modify leave_requests for authenticated" ON leave_requests FOR ALL USING (auth.role() = 'authenticated');

