import {
    Sun,
    Moon,
    Check,
    X,
    User,
    Clock,
    Banknote,
    FileText,
    Bell,
    Settings,
    Briefcase,
    Calendar,
    Users,
    ArrowRightLeft,
    Search,
    Filter,
    MoreHorizontal,
    ChevronDown,
    ChevronUp,
    LogOut,
    LogIn,
    AlertCircle,
    CheckCircle2,
    Trash
} from "lucide-react";

// Re-export specific icons to keep the main code clean and consistent
export const Icons = {
    Sun,
    Moon,
    Check,
    X,
    User,
    Clock,
    Money: Banknote,
    File: FileText,
    Bell,
    Settings,
    Job: Briefcase,
    Calendar,
    Staff: Users,
    Swap: ArrowRightLeft,
    Search,
    Filter,
    More: MoreHorizontal,
    Down: ChevronDown,
    Up: ChevronUp,
    Out: LogOut,
    In: LogIn,
    Alert: AlertCircle,
    Success: CheckCircle2,
    Trash
};
